name: 'mec_education_demo'
version: '1.0.0'
config-version: 2

profile: 'mec_education_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mec_education_demo:
    raw:
      +materialized: view
      +schema: raw
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
