{{
    config(
        materialized='table',
        description='Clusterizacao de UFs por indicadores educacionais usando Z-Score',
        post_hook="CREATE OR REPLACE TABLE `provas-de-conceitos`.`mec_educacao_dev`.`mart_clusters` AS SELECT * FROM {{ this }}"
    )
}}

WITH features AS (
    SELECT
        UF,
        ANO,
        NOTA_MEDIA_ENEM,
        RENDA_MEDIA_FAMILIAR,
        PCT_ESCOLAS_INTERNET,
        PCT_ESCOLAS_LABORATORIO,
        ALUNOS_POR_DOCENTE,
        TOTAL_MATRICULAS,
        TOTAL_DOCENTES
    FROM {{ ref('mart_educacao_uf') }}
    WHERE ANO = (SELECT MAX(ANO) FROM {{ ref('mart_educacao_uf') }})
      AND NOTA_MEDIA_ENEM IS NOT NULL
),

normalized AS (
    SELECT
        UF,
        ANO,
        NOTA_MEDIA_ENEM,
        RENDA_MEDIA_FAMILIAR,
        PCT_ESCOLAS_INTERNET,
        (NOTA_MEDIA_ENEM - AVG(NOTA_MEDIA_ENEM) OVER()) / NULLIF(STDDEV(NOTA_MEDIA_ENEM) OVER(), 0) AS Z_NOTA,
        (RENDA_MEDIA_FAMILIAR - AVG(RENDA_MEDIA_FAMILIAR) OVER()) / NULLIF(STDDEV(RENDA_MEDIA_FAMILIAR) OVER(), 0) AS Z_RENDA,
        (PCT_ESCOLAS_INTERNET - AVG(PCT_ESCOLAS_INTERNET) OVER()) / NULLIF(STDDEV(PCT_ESCOLAS_INTERNET) OVER(), 0) AS Z_INFRA
    FROM features
),

clustered AS (
    SELECT
        UF,
        ANO,
        NOTA_MEDIA_ENEM,
        RENDA_MEDIA_FAMILIAR,
        PCT_ESCOLAS_INTERNET,
        Z_NOTA,
        Z_RENDA,
        Z_INFRA,
        CASE
            WHEN Z_NOTA > 0.5 AND Z_RENDA > 0.5 THEN 1
            WHEN Z_NOTA > 0 AND Z_RENDA > 0 THEN 2
            WHEN Z_NOTA < 0 AND Z_RENDA > 0 THEN 3
            WHEN Z_NOTA < -0.5 AND Z_RENDA < -0.5 THEN 4
            ELSE 3
        END AS CLUSTER_ID
    FROM normalized
),

geo_uf AS (
    SELECT 'AC' AS UF, -9.0247 AS LATITUDE_UF, -70.8120 AS LONGITUDE_UF
    UNION ALL SELECT 'AL', -9.5713, -36.7820
    UNION ALL SELECT 'AP',  1.4102, -51.7720
    UNION ALL SELECT 'AM', -3.4168, -65.8561
    UNION ALL SELECT 'BA', -12.5797, -41.7007
    UNION ALL SELECT 'CE', -5.4984, -39.3206
    UNION ALL SELECT 'DF', -15.7801, -47.9292
    UNION ALL SELECT 'ES', -19.1834, -40.3089
    UNION ALL SELECT 'GO', -15.8270, -49.8362
    UNION ALL SELECT 'MA', -5.4200, -45.4400
    UNION ALL SELECT 'MT', -12.6819, -56.9211
    UNION ALL SELECT 'MS', -20.7722, -54.7852
    UNION ALL SELECT 'MG', -18.5122, -44.5550
    UNION ALL SELECT 'PA', -3.4168, -52.2311
    UNION ALL SELECT 'PB', -7.2399, -36.7820
    UNION ALL SELECT 'PR', -24.8912, -51.5319
    UNION ALL SELECT 'PE', -8.8137, -36.9541
    UNION ALL SELECT 'PI', -7.7183, -42.7289
    UNION ALL SELECT 'RJ', -22.9099, -43.1729
    UNION ALL SELECT 'RN', -5.8127, -36.2089
    UNION ALL SELECT 'RS', -30.0346, -53.2105
    UNION ALL SELECT 'RO', -11.5057, -63.5806
    UNION ALL SELECT 'RR',  1.9903, -61.3300
    UNION ALL SELECT 'SC', -27.2423, -50.2189
    UNION ALL SELECT 'SP', -22.9099, -48.7045
    UNION ALL SELECT 'SE', -10.5741, -37.3857
    UNION ALL SELECT 'TO', -10.1753, -48.2982
)

SELECT
    c.UF,
    c.ANO,
    c.CLUSTER_ID,
    CASE c.CLUSTER_ID
        WHEN 1 THEN 'Alto Desempenho / Alta Renda'
        WHEN 2 THEN 'Desempenho Médio / Renda Média'
        WHEN 3 THEN 'Desempenho em Desenvolvimento (Potencial)'
        WHEN 4 THEN 'Baixo Desempenho / Baixa Renda (Prioritário)'
    END AS DESCRICAO_CLUSTER,
    ROUND(c.NOTA_MEDIA_ENEM, 2) AS NOTA_MEDIA_ENEM,
    ROUND(c.RENDA_MEDIA_FAMILIAR, 2) AS RENDA_MEDIA_FAMILIAR,
    ROUND(c.PCT_ESCOLAS_INTERNET, 2) AS PCT_ESCOLAS_INTERNET,
    ROUND(c.Z_NOTA, 4) AS Z_SCORE_NOTA,
    ROUND(c.Z_RENDA, 4) AS Z_SCORE_RENDA,
    ROUND(c.Z_INFRA, 4) AS Z_SCORE_INFRA,
    CASE c.CLUSTER_ID
        WHEN 4 THEN 'ALTA'
        WHEN 3 THEN 'MEDIA'
        WHEN 2 THEN 'BAIXA'
        WHEN 1 THEN 'MONITORAMENTO'
    END AS PRIORIDADE_INVESTIMENTO,
    g.LATITUDE_UF,
    g.LONGITUDE_UF,
    CONCAT(CAST(g.LATITUDE_UF AS STRING), ',', CAST(g.LONGITUDE_UF AS STRING)) AS LOCALIZACAO_GEO,
    a.STATUS_DESEMPENHO,
    a.GAP_INTERNET_PCT,
    a.GAP_LABORATORIO_PCT,
    a.INVESTIMENTO_TOTAL_ESTIMADO_BRL,
    CURRENT_TIMESTAMP() AS DATA_PROCESSAMENTO
FROM clustered c
LEFT JOIN geo_uf g ON c.UF = g.UF
LEFT JOIN {{ ref('mart_alocacao') }} a ON c.UF = a.UF
ORDER BY CLUSTER_ID DESC, UF
