{{
    config(
        materialized='table'
    )
}}

WITH base_uf AS (
    SELECT
        UF,
        REGIAO,
        ANO,
        TOTAL_MATRICULAS,
        TOTAL_DOCENTES,
        ALUNOS_POR_DOCENTE,
        PCT_ESCOLAS_INTERNET,
        PCT_ESCOLAS_LABORATORIO,
        NOTA_MEDIA_ENEM
    FROM {{ ref('mart_educacao_uf') }}
    WHERE ANO = (SELECT MAX(ANO) FROM {{ ref('mart_educacao_uf') }})
),

gaps AS (
    SELECT
        UF,
        REGIAO,
        ANO,
        TOTAL_MATRICULAS,
        TOTAL_DOCENTES,
        ALUNOS_POR_DOCENTE,

        CASE
            WHEN ALUNOS_POR_DOCENTE > 25 THEN CEIL((TOTAL_MATRICULAS / 25.0) - TOTAL_DOCENTES)
            ELSE 0
        END AS DOCENTES_NECESSARIOS,

        CASE
            WHEN PCT_ESCOLAS_INTERNET < 90 THEN ROUND((90 - PCT_ESCOLAS_INTERNET), 2)
            ELSE 0
        END AS GAP_INTERNET_PCT,

        CASE
            WHEN PCT_ESCOLAS_LABORATORIO < 70 THEN ROUND((70 - PCT_ESCOLAS_LABORATORIO), 2)
            ELSE 0
        END AS GAP_LABORATORIO_PCT,

        NOTA_MEDIA_ENEM,

        CASE
            WHEN NOTA_MEDIA_ENEM < 500 THEN 'CRITICO'
            WHEN NOTA_MEDIA_ENEM < 550 THEN 'ATENCAO'
            WHEN NOTA_MEDIA_ENEM < 600 THEN 'REGULAR'
            ELSE 'ADEQUADO'
        END AS STATUS_DESEMPENHO

    FROM base_uf
),

alocacao AS (
    SELECT
        UF,
        REGIAO,
        ANO,
        TOTAL_MATRICULAS,
        ALUNOS_POR_DOCENTE,
        DOCENTES_NECESSARIOS,
        GAP_INTERNET_PCT,
        GAP_LABORATORIO_PCT,
        STATUS_DESEMPENHO,

        DOCENTES_NECESSARIOS * 8000.0 AS CUSTO_DOCENTES_MENSAL,

        (GAP_INTERNET_PCT / 100.0) * (TOTAL_MATRICULAS / 500.0) * 15000.0 AS CUSTO_INTERNET_ESTIMADO,

        (GAP_LABORATORIO_PCT / 100.0) * (TOTAL_MATRICULAS / 500.0) * 50000.0 AS CUSTO_LABORATORIO_ESTIMADO,

        CASE STATUS_DESEMPENHO
            WHEN 'CRITICO' THEN 1
            WHEN 'ATENCAO' THEN 2
            WHEN 'REGULAR' THEN 3
            ELSE 4
        END AS ORDEM_PRIORIDADE

    FROM gaps
)

SELECT
    UF,
    REGIAO,
    ANO,
    TOTAL_MATRICULAS,
    ALUNOS_POR_DOCENTE,
    DOCENTES_NECESSARIOS,
    ROUND(GAP_INTERNET_PCT, 2) AS GAP_INTERNET_PCT,
    ROUND(GAP_LABORATORIO_PCT, 2) AS GAP_LABORATORIO_PCT,
    STATUS_DESEMPENHO,
    ROUND(CUSTO_DOCENTES_MENSAL, 2) AS CUSTO_DOCENTES_MENSAL_BRL,
    ROUND(CUSTO_INTERNET_ESTIMADO, 2) AS CUSTO_INTERNET_ESTIMADO_BRL,
    ROUND(CUSTO_LABORATORIO_ESTIMADO, 2) AS CUSTO_LABORATORIO_ESTIMADO_BRL,
    ROUND(CUSTO_DOCENTES_MENSAL + CUSTO_INTERNET_ESTIMADO + CUSTO_LABORATORIO_ESTIMADO, 2) AS INVESTIMENTO_TOTAL_ESTIMADO_BRL,
    ORDEM_PRIORIDADE
FROM alocacao
ORDER BY ORDEM_PRIORIDADE, INVESTIMENTO_TOTAL_ESTIMADO_BRL DESC
