{{
    config(
        materialized='table',
        partition_by={
            'field': 'DATA_REFERENCIA',
            'data_type': 'date',
            'granularity': 'year'
        },
        cluster_by=['UF']
    )
}}

WITH censo_agregado AS (
    SELECT
        ANO,
        DATA_REFERENCIA,
        UF,
        ANY_VALUE(REGIAO) AS REGIAO,
        SUM(MATRICULAS_TOTAL) AS TOTAL_MATRICULAS,
        SUM(MATRICULAS_FUNDAMENTAL) AS MATRICULAS_FUNDAMENTAL,
        SUM(MATRICULAS_MEDIO) AS MATRICULAS_MEDIO,
        SUM(DOCENTES_TOTAL) AS TOTAL_DOCENTES,
        COUNT(DISTINCT COD_ESCOLA) AS TOTAL_ESCOLAS,
        AVG(CASE WHEN TEM_INTERNET THEN 1.0 ELSE 0.0 END) * 100 AS PCT_ESCOLAS_INTERNET,
        AVG(CASE WHEN TEM_LABORATORIO THEN 1.0 ELSE 0.0 END) * 100 AS PCT_ESCOLAS_LABORATORIO,
        AVG(CASE WHEN TEM_BIBLIOTECA THEN 1.0 ELSE 0.0 END) * 100 AS PCT_ESCOLAS_BIBLIOTECA
    FROM {{ ref('stg_censo_escolar') }}
    GROUP BY ANO, DATA_REFERENCIA, UF
),

enem_agregado AS (
    SELECT
        ANO,
        UF,
        COUNT(DISTINCT ID_INSCRICAO) AS TOTAL_INSCRITOS,
        AVG(NOTA_MEDIA) AS NOTA_MEDIA_ENEM,
        AVG(NOTA_MATEMATICA) AS NOTA_MEDIA_MATEMATICA,
        AVG(NOTA_REDACAO) AS NOTA_MEDIA_REDACAO,
        AVG(RENDA_FAMILIAR_ESTIMADA) AS RENDA_MEDIA_FAMILIAR,
        STDDEV(NOTA_MEDIA) AS DESVIO_PADRAO_NOTA
    FROM {{ ref('stg_enem') }}
    WHERE PRESENTE_TODAS_PROVAS = TRUE
    GROUP BY ANO, UF
)

SELECT
    c.ANO,
    c.DATA_REFERENCIA,
    c.UF,
    c.REGIAO,

    c.TOTAL_MATRICULAS,
    c.MATRICULAS_FUNDAMENTAL,
    c.MATRICULAS_MEDIO,
    c.TOTAL_DOCENTES,
    c.TOTAL_ESCOLAS,

    ROUND(c.TOTAL_MATRICULAS / NULLIF(c.TOTAL_DOCENTES, 0), 2) AS ALUNOS_POR_DOCENTE,

    ROUND(c.PCT_ESCOLAS_INTERNET, 2) AS PCT_ESCOLAS_INTERNET,
    ROUND(c.PCT_ESCOLAS_LABORATORIO, 2) AS PCT_ESCOLAS_LABORATORIO,
    ROUND(c.PCT_ESCOLAS_BIBLIOTECA, 2) AS PCT_ESCOLAS_BIBLIOTECA,

    COALESCE(e.TOTAL_INSCRITOS, 0) AS TOTAL_INSCRITOS_ENEM,
    ROUND(e.NOTA_MEDIA_ENEM, 2) AS NOTA_MEDIA_ENEM,
    ROUND(e.NOTA_MEDIA_MATEMATICA, 2) AS NOTA_MEDIA_MATEMATICA,
    ROUND(e.NOTA_MEDIA_REDACAO, 2) AS NOTA_MEDIA_REDACAO,
    ROUND(e.RENDA_MEDIA_FAMILIAR, 2) AS RENDA_MEDIA_FAMILIAR,
    ROUND(e.DESVIO_PADRAO_NOTA, 2) AS DESVIO_PADRAO_NOTA,

    CURRENT_TIMESTAMP() AS DATA_CARGA

FROM censo_agregado c
LEFT JOIN enem_agregado e
    ON c.ANO = e.ANO AND c.UF = e.UF
