{{
    config(
        materialized='view',
        description='Dados brutos do ENEM - fonte INEP/MEC'
    )
}}

SELECT
    CAST(NU_INSCRICAO AS STRING) AS ID_INSCRICAO,
    CAST(NU_ANO AS INT64) AS ANO,
    CAST(CO_MUNICIPIO_ESC AS STRING) AS COD_MUNICIPIO,
    CAST(SG_UF_ESC AS STRING) AS UF,

    CASE TP_SEXO
        WHEN 'M' THEN 'Masculino'
        WHEN 'F' THEN 'Feminino'
        ELSE 'Nao Informado'
    END AS SEXO,

    COALESCE(SAFE_CAST(TP_FAIXA_ETARIA AS INT64), 0) AS IDADE,

    CASE TP_COR_RACA
        WHEN 0 THEN 'Nao Declarado'
        WHEN 1 THEN 'Branca'
        WHEN 2 THEN 'Preta'
        WHEN 3 THEN 'Parda'
        WHEN 4 THEN 'Amarela'
        WHEN 5 THEN 'Indigena'
        ELSE 'Nao Declarado'
    END AS COR_RACA,

    CASE Q006
        WHEN 'A' THEN 0
        WHEN 'B' THEN 998
        WHEN 'C' THEN 1497
        WHEN 'D' THEN 1996
        WHEN 'E' THEN 2495
        WHEN 'F' THEN 2994
        WHEN 'G' THEN 3992
        WHEN 'H' THEN 4990
        WHEN 'I' THEN 5988
        WHEN 'J' THEN 6986
        WHEN 'K' THEN 7984
        WHEN 'L' THEN 8982
        WHEN 'M' THEN 9980
        WHEN 'N' THEN 11976
        WHEN 'O' THEN 14970
        WHEN 'P' THEN 19960
        WHEN 'Q' THEN 24950
        ELSE 0
    END AS RENDA_FAMILIAR_ESTIMADA,

    COALESCE(SAFE_CAST(NU_NOTA_CN AS FLOAT64), 0) AS NOTA_CIENCIAS_NATUREZA,
    COALESCE(SAFE_CAST(NU_NOTA_CH AS FLOAT64), 0) AS NOTA_CIENCIAS_HUMANAS,
    COALESCE(SAFE_CAST(NU_NOTA_LC AS FLOAT64), 0) AS NOTA_LINGUAGENS,
    COALESCE(SAFE_CAST(NU_NOTA_MT AS FLOAT64), 0) AS NOTA_MATEMATICA,
    COALESCE(SAFE_CAST(NU_NOTA_REDACAO AS FLOAT64), 0) AS NOTA_REDACAO,

    (TP_PRESENCA_CN = 1 AND TP_PRESENCA_CH = 1 AND
     TP_PRESENCA_LC = 1 AND TP_PRESENCA_MT = 1) AS PRESENTE_TODAS_PROVAS,

    ROUND((
        COALESCE(SAFE_CAST(NU_NOTA_CN AS FLOAT64), 0) +
        COALESCE(SAFE_CAST(NU_NOTA_CH AS FLOAT64), 0) +
        COALESCE(SAFE_CAST(NU_NOTA_LC AS FLOAT64), 0) +
        COALESCE(SAFE_CAST(NU_NOTA_MT AS FLOAT64), 0) +
        COALESCE(SAFE_CAST(NU_NOTA_REDACAO AS FLOAT64), 0)
    ) / 5, 2) AS NOTA_MEDIA,

    DATE(CONCAT(CAST(NU_ANO AS STRING), '-01-01')) AS DATA_REFERENCIA,
    CURRENT_TIMESTAMP() AS DATA_CARGA

FROM {{ source('raw', 'raw_enem_microdados') }}
WHERE NU_ANO IS NOT NULL
  AND NU_INSCRICAO IS NOT NULL
